### ISSUE TITLE
remove dependency on package.xml

### ISSUE THREAD

**Issue by christian-rauch** [UrbanMachine/colcon-poetry-ros#29]
This extension currently requires a `package.xml` to be present. Similar to how [`colcon-cmake`](https://github.com/colcon/colcon-cmake) and [`colcon-ros`](https://github.com/colcon/colcon-ros) work, I suggest that it would make a lot of sense to make this optional.

There could be a package `colcon-poetry` that extracts all information solely from the `pyproject.toml` and a `colcon-poetry-ros` that merges the information from the `pyproject.toml` and `package.xml`. This is useful in order to build "pure" python packages without a `package.xml` that only require python packages available on PyPI, and to have the option to define additional non-python dependencies in a `package.xml`.

**Comment by velovix** [comment]
Thanks for bringing this up! I considered splitting the extension up into pure-Poetry and Poetry+ROS variants, but at the time I didn't understand when that would be useful in practice. When do people make pure Python packages? I could see that being useful if Colcon was a popular tool outside the ROS ecosystem, but I don't know if it is. Do people make pure Python packages even within the context ROS?

**Comment by christian-rauch** [comment]
> When do people make pure Python packages?

Most Python packages are "pure" packages, i.e. do not have a `package.xml`.

> I could see that being useful if Colcon was a popular tool outside the ROS ecosystem, but I don't know if it is.

Colcon may not be popular among Python developers, but Python is certainly popular and colcon is "just" a workspace tool for heterogeneous package sets. You do not have to use ROS in order to use colcon.

> Do people make pure Python packages even within the context ROS?

I would say that most people that use ROS in Python also use other Python packages. And those are not made to work with colcon via an additional metadata file. Also, you can just use colcon without ROS.

With all that said, the basic question remains why require a `package.xml` when all the dependencies can be resolved with a standard `pyproject.toml`? My understanding is that, as long as you only require pure Python dependencies, you should be able to resolve dependencies and build packages just using poetry. The `package.xml` would only be useful when you have to resolve additional non-python dependencies via rosdep.

**Comment by velovix** [comment]
Looking at the code again, it seems it would be pretty easy to accomplish this. I've started work on it.

**Comment by christian-rauch** [comment]
> Looking at the code again, it seems it would be pretty easy to accomplish this. I've started work on it.

Great! I am happy to test this. Let me know if/when I can give it a try.

**Comment by stonier** [comment]
:+1: for this.

**Comment by velovix** [comment]
@christian-rauch I have #32 up to add this feature. Would you mind testing it out with your setup to see if it works for your use-case? It can be installed with this Pip command:

```bash
pip3 install git+https://github.com/UrbanMachine/colcon-poetry-ros.git@0b2b4923b419624b9ce112c73137d5eacbd364e5
```

**Comment by velovix** [comment]
@stonier I think once #32 is merged, any old `pyproject.toml` should work. You won't need special sections like `[tool.colcon-poetry-ros.data-files]` for non-ROS Poetry packages, if that's what you're concerned about. Perhaps there are some ways that a `pyproject.toml` could be configured that would conflict with this extension, but I'm not sure what they would be yet.

**Comment by stonier** [comment]
Oh, indeed. I parsed the README a little too quickly, that custom section is only for ROS files. Excellent.
