### ISSUE TITLE
Docs understanding. Runtime dependencies.

### ISSUE THREAD

**Issue by einspunktnull** [UrbanMachine/colcon-poetry-ros#36]
he guys, thx a lot for this great tool.

i have created a package  with `pyproject.toml`, i took ur's and changed executable path within the `[tool.poetry.scripts]` section. I can `colcon build` this package and `colcon_poetry_ros.dependencies.install` installs `my_package` and it's deps within the `install/my_package/local/lib/python3.10/dist-packages` dir. but when i run  executable with `ros2 run my_package my_executable` i get runtime error `ModuleNotFoundError: No module named 'my_package'`. it seems the installed `dist-packages` are not part of the python path. i thought it will be added automatically or did i misunderstand this?

**Comment by velovix** [comment]
You understood correctly, but I believe this tool has trouble with newer versions of Pip. It's a bug that I need to look into. Would you mind trying again with this version of Pip and letting me know if the behavior changes?

```
pip3 install --upgrade pip==21.2.4
```

**Comment by einspunktnull** [comment]
yes with pip `21.2.4` it indeed works. 
and yes this adds the `pythonpath.sh` to the `install/my_package/share/my_package/hook` dir.
these files are not created with the newer versions pip versions 22.0.2` and `23.1.2`, i initially used.
